"""Build the manually curated SBA gap-closure batch artifacts."""

from __future__ import annotations

import json
import re
from pathlib import Path

from tools.constants import PROJECT_ROOT
from tools.question_generation.sba_gap_closure import SAFE_GOVERNANCE


OUT_DIR = PROJECT_ROOT / "knowledge" / "question-bank" / "sba_expansion"
SWEET_SOURCE = (
    "knowledge/official-wset/study-guide/wset_markdown/"
    "seccion_5_section_2_factors_affecting_the_style_quality_and_price_of_w/"
    "5-5_8_white_and_sweet_winemaking.md"
)
CANADA_SOURCE = (
    "knowledge/official-wset/study-guide/wset_markdown/"
    "seccion_6_section_3_still_wines_of_the_world/6-24_35_canada.md"
)
GERMANY_SOURCE = (
    "knowledge/official-wset/study-guide/wset_markdown/"
    "seccion_6_section_3_still_wines_of_the_world/6-11_22_germany.md"
)
TOKAJ_SOURCE = (
    "knowledge/official-wset/study-guide/wset_markdown/"
    "seccion_6_section_3_still_wines_of_the_world/6-13_24_tokaj.md"
)
BORDEAUX_SOURCE = (
    "knowledge/official-wset/study-guide/wset_markdown/"
    "seccion_6_section_3_still_wines_of_the_world/6-2_13_bordeaux.md"
)
FOOD_SOURCE = (
    "knowledge/official-wset/study-guide/wset_markdown/"
    "seccion_4_section_1_wine_and_the_consumer/4-2_2_wine_with_food.md"
)
SERVICE_SOURCE = (
    "knowledge/official-wset/study-guide/wset_markdown/"
    "seccion_4_section_1_wine_and_the_consumer/4-3_3_storage_and_service_of_wine.md"
)
SHERRY_SOURCE = (
    "knowledge/official-wset/study-guide/wset_markdown/"
    "seccion_8_section_5_fortified_wines_of_the_world/8-1_43_sherry.md"
)
PORT_SOURCE = (
    "knowledge/official-wset/study-guide/wset_markdown/"
    "seccion_8_section_5_fortified_wines_of_the_world/8-2_44_port.md"
)
MUSCAT_SOURCE = (
    "knowledge/official-wset/study-guide/wset_markdown/"
    "seccion_8_section_5_fortified_wines_of_the_world/8-3_45_fortified_muscats.md"
)
MADEIRA_SOURCE = "knowledge/knowledge-map/causal-chains/HC_MADEIRA_HEAT_OXIDATIVE_AGEING.json"
MATURATION_SOURCE = (
    "knowledge/official-wset/study-guide/wset_markdown/"
    "seccion_5_section_2_factors_affecting_the_style_quality_and_price_of_w/"
    "5-4_7_common_elements_in_winemaking_and_maturation.md"
)


def _q(
    ra,
    topic,
    stem,
    correct,
    wrongs,
    cause,
    mechanism,
    effect,
    misconception_id,
    target_error,
    keywords,
    source_files,
):
    return {
        "ra": ra,
        "topic": topic,
        "stem": stem,
        "correct": correct,
        "wrongs": wrongs,
        "cause": cause,
        "mechanism": mechanism,
        "effect": effect,
        "misconception_id": misconception_id,
        "target_error": target_error,
        "keywords": keywords,
        "source_files": source_files,
    }


BATCH_1 = [
    _q("RA1", "icewine_concentration", "Si unas uvas sanas se congelan de forma natural en la vid y se prensan aún congeladas, ¿qué resultado explica mejor la concentración del mosto?", "Parte del agua queda como hielo y se obtiene poco mosto rico en azúcar, acidez y sabor.", ["El hielo se derrite en la prensa y aumenta el rendimiento sin cambiar la concentración.", "La congelación transforma directamente los ácidos en azúcar.", "Las levaduras consumen el agua antes de iniciar la fermentación."], "Las uvas alcanzan temperaturas de congelación en la vid.", "Al prensarlas congeladas, gran parte del agua permanece en la prensa como hielo.", "El rendimiento es bajo y el mosto queda intensamente concentrado.", "MC_ICEWINE_NOBLE_01", "Confundir crioconcentración con botrytis.", ["Icewine", "Eiswein", "congelación", "prensado", "concentración"], [SWEET_SOURCE]),
    _q("RA1", "icewine_harvest_risk", "Si un productor retrasa la vendimia para esperar la congelación necesaria para Eiswein, ¿qué consecuencia es más probable antes de cosechar?", "Aumentan los riesgos de pérdida por podredumbre, aves y caída de fruta.", ["Disminuye toda presión de enfermedad porque el azúcar protege las bayas.", "La fruta gana volumen y eleva el rendimiento de mosto.", "La acidez desaparece por completo antes de que llegue la helada."], "La fruta madura permanece expuesta en la vid durante más tiempo.", "El retraso prolonga la exposición a clima adverso, fauna y deterioro.", "Puede perderse una parte importante de la cosecha antes de la congelación.", "MC_ICEWINE_RESIDUAL_02", "Suponer que esperar la helada no añade riesgo ni coste.", ["Eiswein", "vendimia tardía", "riesgo", "bajo rendimiento"], [SWEET_SOURCE, GERMANY_SOURCE]),
    _q("RA1", "icewine_vs_botrytis", "Al comparar crioconcentración y podredumbre noble, ¿qué factor explica mejor que ambos métodos den vinos dulces pero con perfiles distintos?", "La congelación separa agua físicamente, mientras Botrytis perfora la piel y modifica compuestos de la uva.", ["Ambos métodos dependen de que la levadura detenga la fermentación al mismo nivel de alcohol.", "Los dos métodos convierten la acidez de la uva en glicerol.", "La única diferencia es el momento del embotellado."], "Dos mecanismos diferentes reducen la proporción de agua respecto de los solutos.", "El hielo retiene agua en un caso; el hongo causa evaporación y cambios metabólicos en el otro.", "Ambos concentran, pero Botrytis aporta un carácter aromático y químico propio.", "MC_ICEWINE_NOBLE_01", "Tratar Icewine y vino botritizado como el mismo proceso.", ["Icewine", "Botrytis", "crioconcentración", "deshidratación"], [SWEET_SOURCE]),
    _q("RA1", "icewine_press_yield", "Si la bodega prensa uvas completamente congeladas para Icewine, ¿qué consecuencia productiva explica mejor su precio elevado?", "Se extrae una fracción pequeña de mosto concentrado por kilogramo de uva.", ["Se obtiene más mosto porque los cristales rompen todas las paredes celulares.", "El alcohol final sube sin necesidad de fermentación.", "El vino puede embotellarse sin clarificación ni estabilización."], "El agua de las bayas está inmovilizada como hielo.", "La prensa libera sobre todo la fracción líquida más concentrada.", "El bajo rendimiento y la cosecha arriesgada elevan el coste por botella.", "MC_ICEWINE_RESIDUAL_02", "Asumir que congelar aumenta el rendimiento.", ["Icewine", "prensado", "rendimiento", "coste"], [SWEET_SOURCE]),
    _q("RA2", "canada_icewine_acidity", "Un Icewine canadiense conserva acidez alta pese a su intenso dulzor. ¿Qué factor explica mejor ese equilibrio?", "La fruta se cultiva en clima frío y se concentra sin eliminar toda la acidez natural.", ["La congelación añade ácido tartárico nuevo a las bayas.", "La elevada azúcar residual hace que la acidez deje de ser perceptible.", "La fermentación maloláctica siempre aumenta la acidez."], "La maduración ocurre en un entorno fresco y la fruta se cosecha muy tarde.", "La crioconcentración aumenta azúcar y sabor mientras permanece una base ácida importante.", "El vino puede ser muy dulce sin resultar necesariamente pesado o plano.", "MC_ACIDITY_02", "Creer que un vino muy dulce no puede tener acidez alta.", ["Canadá", "Icewine", "acidez", "equilibrio"], [CANADA_SOURCE, SWEET_SOURCE]),
    _q("RA2", "canada_icewine_vintage", "Si un invierno canadiense no alcanza a tiempo temperaturas suficientemente bajas, ¿qué consecuencia es más probable para un productor de Icewine?", "Puede no reunir condiciones para cosechar fruta congelada y perder parte o toda la producción prevista.", ["Puede congelar el vino terminado y venderlo con la misma indicación.", "La falta de helada favorece automáticamente una concentración mayor.", "Puede sustituir la congelación por flor sin cambiar el estilo."], "La producción depende de una helada natural mientras la fruta sigue sana en la vid.", "Sin frío suficiente no se separa agua como hielo durante el prensado.", "La disponibilidad y el volumen varían mucho entre añadas.", "MC_ICEWINE_NOBLE_01", "Ignorar la dependencia de una congelación natural.", ["Canadá", "Icewine", "helada", "variación de añada"], [CANADA_SOURCE]),
    _q("RA2", "canada_icewine_harvest", "Si el productor cosecha las uvas de Icewine antes de que estén congeladas, ¿qué resultado es más probable?", "El prensado no producirá la misma crioconcentración y el mosto será menos concentrado.", ["El mosto será más concentrado porque las bayas estarán más blandas.", "La fermentación se detendrá automáticamente por el frío residual.", "Aparecerán aromas botritizados aunque no haya Botrytis."], "La separación de agua requiere cristales de hielo presentes al prensar.", "La fruta no congelada libera agua y solutos juntos.", "Se pierde el mecanismo que distingue la concentración del Icewine.", "MC_ICEWINE_RESIDUAL_02", "Pensar que basta una vendimia tardía sin congelación.", ["Canadá", "Icewine", "cosecha", "crioconcentración"], [CANADA_SOURCE, SWEET_SOURCE]),
    _q("RA2", "canada_icewine_variety_style", "Dos productores canadienses elaboran Icewine, uno con Riesling y otro con Vidal. ¿Qué factor explica mejor que ambos puedan equilibrar azúcar intensa?", "La acidez natural de la fruta y su conservación durante la concentración sostienen el equilibrio.", ["El nivel de azúcar elimina cualquier diferencia varietal.", "La congelación produce taninos altos en ambas variedades.", "Ambos deben criarse bajo flor para conservar frescura."], "Las variedades aptas mantienen estructura ácida al madurar.", "La crioconcentración intensifica el mosto y exige una base estructural suficiente.", "El dulzor puede quedar equilibrado por acidez marcada y sabor concentrado.", "MC_ACIDITY_01", "Separar dulzor y acidez como si no interactuaran.", ["Canadá", "Riesling", "Vidal", "Icewine", "acidez"], [CANADA_SOURCE]),
    _q("RA2", "canada_icewine_cost", "¿Qué factor explica mejor que un Icewine canadiense suela tener un coste de producción alto?", "Vendimia arriesgada y tardía, selección exigente y rendimiento de prensado muy bajo.", ["Fermentación rápida a alta temperatura y gran rendimiento por hectárea.", "Ausencia de pérdidas porque la fruta permanece protegida por el hielo.", "Uso obligatorio de roble nuevo durante décadas."], "La fruta queda en la vid hasta el invierno y se prensa congelada.", "Aumentan la exposición a pérdidas, la necesidad de mano de obra y la proporción de sólidos retenidos.", "Pocas botellas absorben costes altos de viticultura y elaboración.", "MC_ICEWINE_RESIDUAL_02", "Atribuir el precio solo al dulzor o al marketing.", ["Canadá", "Icewine", "coste", "bajo rendimiento"], [CANADA_SOURCE, SWEET_SOURCE]),
    _q("RA2", "canada_icewine_botrytis_incidental", "Un lote de uvas para Icewine muestra algo de Botrytis, pero alcanzó la concentración al congelarse. ¿Qué interpretación explica mejor el estilo?", "La congelación sigue siendo el mecanismo definitorio; Botrytis puede ser incidental y modificar el perfil.", ["La presencia de Botrytis convierte automáticamente el vino en Sauternes.", "La congelación deja de tener efecto cuando aparece cualquier hongo.", "El vino solo puede ser seco porque los dos mecanismos se neutralizan."], "La fruta puede sufrir más de una influencia antes de cosecharse.", "La helada separa agua como hielo aunque existan bayas afectadas por Botrytis.", "El carácter principal procede de la crioconcentración, con posibles matices adicionales.", "MC_ICEWINE_NOBLE_01", "Creer que Botrytis es obligatorio o redefine por completo Icewine.", ["Canadá", "Icewine", "Botrytis", "mecanismo"], [CANADA_SOURCE, SWEET_SOURCE]),
    _q("RA2", "germany_eiswein_acidity", "¿Qué factor explica mejor que un Eiswein alemán pueda mostrar dulzor intenso y acidez muy alta?", "La uva conserva acidez en un clima fresco y la congelación concentra el mosto sin requerir sobremaduración botritizada.", ["La helada convierte azúcar en ácido málico.", "La legislación obliga a acidificar todos los Eiswein.", "La crianza oxidativa incrementa la acidez total."], "La fruta madura en una región de clima fresco y permanece sana hasta la helada.", "El agua congelada se separa en la prensa y concentra los componentes presentes.", "Azúcar, sabor y acidez intensa pueden coexistir en el vino.", "MC_ACIDITY_02", "Suponer que la concentración dulce elimina la acidez.", ["Alemania", "Eiswein", "acidez", "congelación"], [GERMANY_SOURCE, SWEET_SOURCE]),
    _q("RA2", "germany_eiswein_vs_tba", "Al comparar Eiswein y Trockenbeerenauslese, ¿qué opción explica mejor la diferencia de producción?", "Eiswein depende de uvas congeladas sanas o no necesariamente botritizadas; TBA depende de bayas muy afectadas por podredumbre noble.", ["Ambos dependen exclusivamente de secado en esteras.", "Eiswein se fortifica durante la fermentación y TBA después.", "TBA se concentra por hielo y Eiswein por flor."], "Los estilos parten de mecanismos distintos de concentración.", "Uno retiene agua como hielo; el otro pierde agua por bayas intensamente botritizadas.", "Pueden compartir dulzor elevado, pero no la misma causa ni el mismo perfil.", "MC_ICEWINE_NOBLE_01", "Confundir Eiswein con TBA.", ["Alemania", "Eiswein", "TBA", "Botrytis"], [GERMANY_SOURCE, SWEET_SOURCE]),
    _q("RA2", "canada_icewine_fermentation", "Un mosto de Icewine tiene concentración de azúcar muy alta. ¿Qué consecuencia es más probable durante la fermentación?", "La levadura trabaja bajo fuerte presión osmótica y la fermentación puede ser lenta o detenerse con azúcar residual.", ["La alta concentración garantiza una fermentación completa y rápida.", "El mosto no puede producir alcohol porque toda el agua está congelada.", "La fermentación convierte toda la acidez en dióxido de carbono."], "El mosto contiene una proporción muy alta de azúcar disuelta.", "La presión osmótica y el alcohol creciente dificultan la actividad de la levadura.", "Es probable conservar azúcar residual y requerir control cuidadoso.", "MC_RESIDUAL_SUGAR_SWEET_01", "Pensar que todo azúcar elevado fermenta necesariamente hasta sequedad.", ["Icewine", "fermentación", "presión osmótica", "azúcar residual"], [SWEET_SOURCE, CANADA_SOURCE]),
    _q("RA2", "canada_icewine_style", "Si un Icewine combina azúcar residual alta, acidez alta y sabores concentrados, ¿qué resultado sensorial es más probable?", "Un vino dulce, intenso y de cuerpo pleno cuya acidez evita una sensación empalagosa.", ["Un vino seco y ligero porque la acidez neutraliza químicamente el azúcar.", "Un vino tánico porque el hielo extrae compuestos de los raspones.", "Un vino neutro porque la congelación elimina los aromas."], "El mosto concentra azúcar, ácidos y compuestos de sabor.", "La fermentación deja azúcar residual mientras la acidez aporta contraste estructural.", "El vino resulta rico e intenso, pero puede conservar equilibrio y longitud.", "MC_SWEET_BALANCING_02", "Confundir dulzor alto con falta automática de equilibrio.", ["Icewine", "dulzor", "acidez", "cuerpo", "intensidad"], [CANADA_SOURCE, SWEET_SOURCE]),
    _q("RA2", "sauternes_morning_mist", "En Sauternes, ¿qué secuencia meteorológica explica mejor el desarrollo de podredumbre noble en lugar de podredumbre gris?", "Mañanas húmedas o con niebla favorecen la infección y tardes cálidas y secas permiten la evaporación.", ["Lluvia continua mantiene las bayas mojadas hasta que se diluyen.", "Heladas intensas cada noche congelan el agua dentro de la baya.", "Viento seco permanente impide toda infección por Botrytis."], "Las bayas maduras reciben humedad suficiente para que Botrytis se establezca.", "Periodos secos posteriores limitan la podredumbre destructiva y permiten pérdida de agua.", "Las bayas se arrugan y concentran azúcar y sabor con carácter noble.", "MC_BOTRYTIS_01", "Creer que cualquier humedad produce podredumbre noble.", ["Sauternes", "Botrytis", "niebla", "tiempo seco"], [BORDEAUX_SOURCE, SWEET_SOURCE]),
    _q("RA2", "sauternes_selective_picking", "Si la podredumbre noble avanza de forma desigual dentro de una parcela de Sauternes, ¿qué decisión explica mejor la necesidad de varias pasadas de vendimia?", "Seleccionar solo las bayas adecuadamente botritizadas en cada pasada.", ["Cosechar todo a la vez para igualar el grado de Botrytis.", "Esperar a que todas las bayas se conviertan en pasas secas.", "Vendimiar mecánicamente para mezclar fruta sana y dañada."], "Botrytis no afecta todas las bayas al mismo ritmo.", "Las cuadrillas vuelven varias veces y eligen fruta en el punto adecuado.", "Mejora la concentración y pureza, pero suben mano de obra, riesgo y coste.", "MC_SAUTERNES_HARVEST_01", "Reducir la vendimia de Sauternes a un único nivel fijo de azúcar.", ["Sauternes", "selección", "tries", "Botrytis"], [BORDEAUX_SOURCE]),
    _q("RA2", "sauternes_semillon", "¿Qué factor explica mejor la importancia de Sémillon en muchos Sauternes?", "Su piel relativamente fina favorece la infección por Botrytis y aporta cuerpo al vino.", ["Su piel gruesa impide toda pérdida de agua.", "Su tanino alto estabiliza el color tinto.", "Su baja susceptibilidad permite vendimia mecánica temprana."], "La variedad se cultiva en condiciones favorables para noble rot.", "La piel susceptible facilita la acción del hongo y la concentración de la baya.", "Contribuye riqueza, textura y carácter botritizado al ensamblaje.", "MC_SAUTERNES_HARVEST_01", "Explicar Sauternes solo por azúcar sin considerar variedad y Botrytis.", ["Sauternes", "Sémillon", "piel fina", "Botrytis"], [BORDEAUX_SOURCE]),
    _q("RA2", "sauternes_sauvignon", "Si un ensamblaje de Sauternes incorpora Sauvignon Blanc junto con Sémillon, ¿qué resultado de estilo es más probable?", "Mayor frescura aromática y acidez para equilibrar la riqueza del Sémillon botritizado.", ["Más tanino y color porque Sauvignon Blanc aporta antocianos.", "Menor acidez porque la variedad siempre completa MLF.", "Un estilo biológico porque Sauvignon Blanc genera flor."], "El vino base combina variedades con contribuciones diferentes.", "Sauvignon Blanc aporta acidez y expresión aromática dentro de una matriz rica.", "El ensamblaje puede resultar más fresco y equilibrado.", "MC_ACIDITY_01", "Ignorar el papel estructural de la acidez en vinos dulces.", ["Sauternes", "Sauvignon Blanc", "Sémillon", "equilibrio"], [BORDEAUX_SOURCE]),
    _q("RA2", "sauternes_botrytis_acid", "Si Botrytis concentra una baya pero también metaboliza parte de sus ácidos, ¿qué resultado explica mejor la acidez final de un Sauternes?", "La acidez puede seguir siendo importante, pero no aumenta en la misma proporción que el azúcar por simple concentración.", ["La acidez siempre se duplica exactamente con el azúcar.", "Botrytis elimina toda acidez y vuelve plano cualquier vino.", "La concentración no afecta azúcar ni sabor."], "La pérdida de agua concentra los solutos de la baya.", "Al mismo tiempo, el hongo consume parte de ciertos ácidos.", "El vino necesita suficiente acidez restante para equilibrar su gran dulzor.", "MC_BOTRYTIS_01", "Aplicar una regla de concentración idéntica a todos los componentes.", ["Sauternes", "Botrytis", "acidez", "concentración"], [BORDEAUX_SOURCE, SWEET_SOURCE]),
    _q("RA2", "sauternes_vintage_risk", "Si durante la vendimia de Sauternes llega lluvia persistente después de iniciarse Botrytis, ¿qué consecuencia es más probable?", "Aumenta el riesgo de podredumbre gris, dilución y pérdida de fruta.", ["La lluvia garantiza una concentración más rápida y uniforme.", "La fruta se congela y pasa a ser Eiswein.", "La humedad detiene toda actividad del hongo."], "Las bayas botritizadas y maduras son frágiles durante una cosecha prolongada.", "La humedad continua favorece deterioro y reduce la evaporación necesaria.", "La calidad y el volumen pueden caer con rapidez.", "MC_BOTRYTIS_01", "Creer que más humedad siempre mejora noble rot.", ["Sauternes", "lluvia", "podredumbre gris", "riesgo"], [BORDEAUX_SOURCE]),
    _q("RA2", "sauternes_oak", "Si un Sauternes concentrado fermenta o madura en roble nuevo, ¿qué resultado de estilo es más probable?", "Mayor complejidad de vainilla y especias, con integración lenta de una estructura rica.", ["Pérdida inmediata de todo azúcar residual.", "Desarrollo de taninos propios de un tinto muy extraído.", "Aromas de flor y acetaldehído por crianza biológica."], "Un vino concentrado entra en contacto con madera nueva y pequeñas cantidades de oxígeno.", "El roble aporta compuestos aromáticos y la maduración integra textura y sabores.", "El estilo gana complejidad, coste y potencial de evolución.", "MC_OAK_QUALITY_01", "Suponer que el roble crea calidad por sí solo o elimina el dulzor.", ["Sauternes", "roble", "vainilla", "maduración"], [BORDEAUX_SOURCE, SWEET_SOURCE]),
    _q("RA2", "sauternes_quality_balance", "Dos Sauternes tienen el mismo azúcar residual, pero uno posee mayor acidez, intensidad y longitud. ¿Qué factor explica mejor que se perciba de mayor calidad?", "El segundo muestra mejor equilibrio, concentración y persistencia, no solo mayor dulzor.", ["El azúcar residual fija por sí solo la calidad.", "La menor acidez siempre indica mayor madurez y calidad.", "La intensidad aromática importa únicamente en vinos secos."], "La calidad sensorial depende de varios componentes estructurales y aromáticos.", "Acidez, concentración y longitud sostienen el dulzor y evitan desequilibrio.", "El vino ofrece mayor definición y persistencia.", "MC_SWEET_BALANCING_02", "Equiparar dulzor con calidad.", ["Sauternes", "calidad", "equilibrio", "longitud"], [BORDEAUX_SOURCE]),
    _q("RA2", "tokaji_aszu_addition", "Si un productor añade bayas Aszú seleccionadas a mosto en fermentación o vino base, ¿qué resultado explica mejor el estilo posterior?", "La maceración transfiere azúcar, acidez, sabor concentrado y carácter botritizado al líquido.", ["Las bayas eliminan todo alcohol ya formado.", "La adición crea burbujas por una segunda fermentación en botella.", "El vino se vuelve seco porque la pasta absorbe azúcar."], "Las bayas Aszú están deshidratadas y concentradas por noble rot.", "El contacto y la maceración extrae sus componentes al vino base.", "Aumentan dulzor, concentración y complejidad manteniendo acidez.", "MC_TOKAJI_QUALITY_01", "Tratar la adición de Aszú como simple aromatización.", ["Tokaji", "Aszú", "bayas botritizadas", "maceración"], [TOKAJ_SOURCE]),
    _q("RA2", "tokaji_furmint", "¿Qué factor explica mejor que Furmint sea útil para Tokaji Aszú de larga vida?", "Su acidez alta equilibra el dulzor y sostiene la evolución del vino.", ["Su tanino alto permite una extracción prolongada de hollejos.", "Su acidez baja hace innecesaria la selección de fruta.", "Su neutralidad impide cualquier aroma botritizado."], "Furmint puede madurar con azúcar elevado conservando acidez marcada.", "La acidez aporta estructura frente a la concentración y el azúcar residual.", "El vino puede ser intenso, equilibrado y longevo.", "MC_ACIDITY_02", "Suponer que el dulzor basta para conservar y equilibrar Tokaji.", ["Tokaji", "Furmint", "acidez", "longevidad"], [TOKAJ_SOURCE]),
    _q("RA2", "tokaji_szamorodni", "Si se cosechan racimos completos que mezclan bayas sanas y botritizadas para Szamorodni, ¿qué consecuencia de estilo es más probable frente a seleccionar bayas Aszú individualmente?", "El grado de concentración depende de la proporción natural de bayas botritizadas del racimo.", ["El vino siempre será más dulce que cualquier Tokaji Aszú.", "La mezcla elimina la influencia de Botrytis.", "El método exige congelar el racimo antes de prensarlo."], "Los racimos contienen una mezcla variable de fruta sana y afectada.", "La cosecha conjunta incorpora esa proporción directamente al mosto.", "El estilo puede variar de seco a dulce y suele ser menos extremo que una selección Aszú intensa.", "MC_TOKAJI_QUALITY_01", "Interpretar todas las categorías de Tokaji como una escala única de dulzor.", ["Tokaji", "Szamorodni", "racimos", "Botrytis"], [TOKAJ_SOURCE]),
    _q("RA2", "tokaji_essencia", "Si el mosto de escurrido libre de bayas Aszú contiene una concentración extrema de azúcar, ¿qué consecuencia es más probable durante la fermentación de Eszencia?", "La fermentación avanza muy lentamente y alcanza alcohol muy bajo con enorme azúcar residual.", ["La levadura fermenta con rapidez hasta alcohol alto y sequedad.", "El azúcar se convierte principalmente en tanino.", "La concentración obliga a una crianza biológica bajo flor."], "El jugo contiene una cantidad excepcional de azúcar y poca agua disponible.", "La presión osmótica limita fuertemente la actividad de la levadura.", "Se obtiene un líquido muy dulce, intenso y de alcohol muy bajo.", "MC_RESIDUAL_SUGAR_SWEET_01", "Creer que más azúcar siempre produce más alcohol.", ["Tokaji", "Eszencia", "fermentación lenta", "alcohol bajo"], [TOKAJ_SOURCE]),
    _q("RA2", "tokaji_puttonyos", "Dos Tokaji declaran una categoría Aszú comparable, pero muestran distinta percepción de dulzor. ¿Qué factor explica mejor la diferencia?", "La percepción final también depende de acidez, fermentación, vino base y equilibrio, no solo de la declaración.", ["La categoría determina una sensación idéntica en todos los vinos.", "El roble nuevo convierte automáticamente azúcar en acidez.", "La añada no puede modificar concentración ni equilibrio."], "La clasificación describe un estilo y una concentración mínima, no toda la experiencia sensorial.", "Composición del vino base, acidez, fermentación y crianza modulan el resultado.", "Vinos de categoría similar pueden mostrar distinto equilibrio y perfil.", "MC_TOKAJI_QUALITY_01", "Usar puttonyos como lectura absoluta de dulzor percibido.", ["Tokaji", "puttonyos", "dulzor", "acidez"], [TOKAJ_SOURCE]),
    _q("RA2", "tokaji_botrytis_conditions", "Si el otoño en Tokaj permanece húmedo sin periodos secos, ¿qué consecuencia es más probable para la fruta destinada a Aszú?", "Aumenta el riesgo de podredumbre gris en vez de una deshidratación noble controlada.", ["La concentración mejora indefinidamente porque toda humedad favorece Aszú.", "Las bayas se congelan y se convierten en Eiswein.", "Botrytis deja de infectar por completo en presencia de agua."], "Botrytis necesita humedad para infectar, pero también periodos secos.", "Sin secado, la baya puede deteriorarse en lugar de perder agua de forma beneficiosa.", "Bajan la proporción de fruta seleccionable y el potencial de calidad.", "MC_BOTRYTIS_01", "Creer que humedad continua equivale a noble rot.", ["Tokaji", "Botrytis", "humedad", "periodos secos"], [TOKAJ_SOURCE]),
    _q("RA2", "tokaji_harslevelu", "Si Hárslevelű se mezcla con Furmint en Tokaji, ¿qué resultado de estilo es más probable?", "Puede aportar un perfil más perfumado mientras Furmint conserva la columna de acidez.", ["Aumenta tanino y color como una variedad tinta.", "Elimina el carácter de Botrytis por completo.", "Obliga a terminar el vino seco."], "Las variedades del ensamblaje aportan rasgos complementarios.", "Hárslevelű contribuye expresión aromática y Furmint estructura ácida.", "El vino puede combinar perfume, riqueza y equilibrio.", "MC_TOKAJI_QUALITY_01", "Reducir el estilo de Tokaji a una sola variedad o al azúcar.", ["Tokaji", "Hárslevelű", "Furmint", "ensamblaje"], [TOKAJ_SOURCE]),
    _q("RA2", "tokaji_ageing", "Si un Tokaji Aszú concentrado madura durante un periodo prolongado, ¿qué resultado de estilo es más probable?", "Desarrolla mayor integración y complejidad de frutos secos, miel y especias sin perder necesariamente su acidez.", ["Se vuelve espumoso por presión acumulada.", "Pierde todo azúcar residual por evaporación.", "Adquiere tanino alto por contacto con hollejos tintos."], "El vino contiene alta concentración, azúcar, acidez y compuestos botritizados.", "La maduración lenta integra componentes y favorece aromas terciarios.", "Aumentan complejidad y armonía con potencial de larga evolución.", "MC_AGEING_IMPROVEMENT_01", "Suponer que la edad mejora cualquier vino o elimina el dulzor.", ["Tokaji", "Aszú", "maduración", "complejidad"], [TOKAJ_SOURCE]),
    _q("RA2", "late_harvest", "Si un productor deja uvas sanas en la vid después de la madurez normal sin esperar Botrytis ni helada, ¿qué resultado es más probable?", "Mayor concentración de azúcar y sabores maduros por sobremaduración y algo de pérdida de agua.", ["Aromas nobles de Botrytis aparecen obligatoriamente.", "El agua queda separada como hielo durante el prensado.", "El vino debe ser fortificado para conservar cualquier azúcar."], "La fruta continúa madurando y puede deshidratarse parcialmente en la vid.", "Sube la relación de azúcar y sabor respecto al agua.", "El mosto puede dar un vino más rico y dulce, con riesgo de menor acidez.", "MC_SWEET_CONCENTRATION_01", "Confundir vendimia tardía con Botrytis o congelación.", ["vendimia tardía", "sobremaduración", "concentración", "acidez"], [SWEET_SOURCE]),
    _q("RA2", "passito_drying", "Si unas uvas se secan después de la vendimia antes de fermentar, ¿qué resultado explica mejor un vino passito?", "La evaporación de agua concentra azúcar, acidez y sabores, mientras cae el rendimiento de mosto.", ["El secado diluye el azúcar al romper las pieles.", "La fruta desarrolla flor y envejecimiento biológico.", "El método elimina toda posibilidad de oxidación."], "Las uvas cosechadas se exponen a condiciones de secado controlado.", "Pierden agua antes del prensado y aumentan los solutos por unidad de volumen.", "El mosto resulta concentrado, rico y escaso.", "MC_SWEET_CONCENTRATION_01", "Creer que solo Botrytis concentra vinos dulces.", ["passito", "secado", "evaporación", "bajo rendimiento"], [SWEET_SOURCE]),
    _q("RA2", "drying_airflow", "Si durante el secado de uvas para vino dulce falta ventilación, ¿qué consecuencia es más probable?", "Aumenta el riesgo de podredumbre no deseada en lugar de una deshidratación limpia.", ["La concentración se vuelve más uniforme y segura.", "La falta de aire congela el agua de las bayas.", "El azúcar se transforma en alcohol antes del prensado."], "Las bayas húmedas permanecen juntas durante un periodo prolongado.", "Sin circulación de aire, la humedad se acumula y favorece microorganismos.", "Puede perderse fruta y aparecer carácter defectuoso.", "MC_SWEET_CONCENTRATION_01", "Suponer que cualquier deshidratación ocurre sin riesgo microbiológico.", ["uvas secadas", "ventilación", "podredumbre", "deshidratación"], [SWEET_SOURCE]),
    _q("RA2", "sweet_fermentation_arrest", "Si una bodega enfría y filtra un vino dulce antes de que la levadura consuma todo el azúcar, ¿qué resultado es más probable?", "Queda azúcar residual y la eliminación de levaduras reduce el riesgo de reinicio de fermentación.", ["El vino se vuelve más dulce porque el frío crea azúcar nuevo.", "La filtración aumenta el alcohol después del embotellado.", "El proceso concentra el mosto mediante evaporación."], "La fermentación todavía contiene levaduras activas y azúcar.", "El frío frena la actividad y la filtración retira células de levadura.", "Se conserva dulzor y mejora la estabilidad microbiológica si el proceso es eficaz.", "MC_RESIDUAL_SUGAR_SWEET_01", "Confundir parada de fermentación con concentración de azúcar.", ["vino dulce", "parada de fermentación", "filtración", "azúcar residual"], [SWEET_SOURCE]),
    _q("RA2", "sweet_must_concentration", "Si un productor concentra mosto antes de fermentar, ¿qué consecuencia estilística es más probable respecto a un mosto sin concentrar?", "Mayor azúcar potencial, cuerpo y sabor, con más dificultad fermentativa.", ["Menor alcohol potencial porque hay menos azúcar.", "Desaparición automática de la acidez.", "Menor presión osmótica para la levadura."], "El mosto empieza con más solutos por unidad de agua.", "La levadura encuentra más azúcar y mayor presión osmótica.", "Puede producirse un vino más rico, alcohólico o dulce según cuánto fermente.", "MC_RESIDUAL_SUGAR_SWEET_01", "Asumir que concentración y fermentación no interactúan.", ["mosto concentrado", "azúcar potencial", "cuerpo", "fermentación"], [SWEET_SOURCE]),
    _q("RA2", "sweet_balance_acidity", "Dos vinos dulces tienen igual azúcar residual; uno procede de fruta con acidez claramente mayor. ¿Qué resultado es más probable?", "El vino de mayor acidez se percibe más fresco y equilibrado.", ["Se percibe siempre más dulce porque ácido y azúcar se suman.", "Tiene necesariamente más tanino.", "Pierde intensidad aromática por neutralización química."], "El dulzor y la acidez actúan simultáneamente en la estructura.", "La acidez contrasta con el azúcar y eleva la sensación de frescura.", "El vino puede sostener mejor la riqueza y el final.", "MC_ACIDITY_01", "Evaluar el dulzor sin considerar la acidez.", ["vino dulce", "acidez", "equilibrio", "frescura"], [SWEET_SOURCE]),
    _q("RA2", "sweet_low_acid", "Si un vino dulce concentrado tiene acidez baja, ¿qué consecuencia sensorial es más probable?", "Puede resultar pesado, empalagoso y con menor definición.", ["La baja acidez vuelve el vino automáticamente seco.", "El dulzor se transforma en tanino.", "El final se alarga siempre por falta de acidez."], "El vino contiene azúcar y cuerpo elevados con poco contraste ácido.", "Falta tensión para equilibrar la riqueza y refrescar el paladar.", "El dulzor domina y reduce la sensación de precisión.", "MC_SWEET_BALANCING_02", "Creer que concentración alta garantiza equilibrio.", ["vino dulce", "acidez baja", "empalagoso", "equilibrio"], [SWEET_SOURCE]),
    _q("RA2", "sweet_botrytis_aroma", "Si Botrytis noble se desarrolla de forma beneficiosa, ¿qué resultado aromático es más probable además de la concentración?", "Mayor complejidad con notas como miel, albaricoque seco y azafrán.", ["Aromas exclusivos de fruta verde sin cambio.", "Carácter de acetaldehído propio de flor.", "Aromas de hielo y agua mineral creados por congelación."], "El hongo actúa metabólicamente sobre bayas maduras mientras pierden agua.", "Se modifican precursores y se concentran compuestos aromáticos.", "El vino muestra un perfil botritizado complejo y reconocible.", "MC_BOTRYTIS_01", "Tratar Botrytis como simple pérdida de agua.", ["Botrytis", "miel", "albaricoque seco", "azafrán"], [SWEET_SOURCE]),
    _q("RA2", "sweet_drying_vs_botrytis", "Al comparar uvas secadas después de la cosecha con uvas afectadas por podredumbre noble, ¿qué factor explica mejor una diferencia aromática entre los vinos?", "Botrytis modifica químicamente la baya, mientras el secado sano concentra sin aportar el mismo carácter fúngico.", ["El secado siempre produce acetaldehído de flor.", "Botrytis concentra solo por congelación.", "Los dos métodos generan perfiles idénticos si el azúcar final coincide."], "Ambos métodos reducen agua, pero solo uno implica metabolismo fúngico.", "Botrytis perfora y transforma la baya; el secado controlado favorece evaporación sin esa acción.", "Los vinos pueden compartir concentración pero mostrar complejidad aromática distinta.", "MC_SWEET_CONCENTRATION_01", "Suponer que igual concentración produce el mismo estilo.", ["vino dulce", "secado", "Botrytis", "perfil aromático"], [SWEET_SOURCE]),
    _q("RA2", "germany_beerenauslese_selection", "Si Botrytis afecta de forma irregular las bayas destinadas a Beerenauslese, ¿qué decisión explica mejor un vino de mayor concentración y pureza?", "Seleccionar individualmente las bayas maduras y botritizadas adecuadas.", ["Cosechar mecánicamente todos los racimos antes de la infección.", "Mezclar fruta podrida gris para elevar el rendimiento.", "Prensar las bayas sin revisar su estado sanitario."], "La infección beneficiosa y la madurez varían dentro de la parcela.", "La selección separa fruta concentrada sana de bayas insuficientes o deterioradas.", "El mosto gana precisión y concentración, aunque aumenta el coste y baja el rendimiento.", "MC_BOTRYTIS_01", "Creer que toda fruta afectada por Botrytis tiene igual calidad.", ["Alemania", "Beerenauslese", "selección", "Botrytis"], [GERMANY_SOURCE, SWEET_SOURCE]),
    _q("RA5", "sweet_pairing_dessert", "Si un restaurante sirve un postre más dulce que el vino elegido, ¿qué consecuencia es más probable para la percepción del vino?", "El vino parecerá menos frutal, más seco, más ácido y posiblemente amargo.", ["El vino parecerá más dulce y más afrutado.", "La comida reducirá toda percepción de acidez.", "El vino desarrollará más alcohol en la copa."], "La comida presenta mayor intensidad de dulzor que el vino.", "El contraste reduce el dulzor percibido del vino y expone acidez y amargor.", "El maridaje puede resultar duro y desequilibrado.", "MC_SWEET_BALANCING_02", "Suponer que cualquier vino dulce funciona con cualquier postre.", ["RA5", "maridaje", "postre", "dulzor"], [FOOD_SOURCE]),
    _q("RA5", "sweet_pairing_blue_cheese", "Al comparar un vino dulce intenso con un queso azul salado, ¿qué factor explica mejor que el maridaje pueda funcionar?", "El dulzor contrasta la sal y la intensidad del vino puede igualar la del queso.", ["La sal convierte químicamente el vino en seco.", "El queso elimina el alcohol del vino.", "La acidez del vino desaparece al contacto con grasa."], "El alimento combina sal, grasa y sabor intenso.", "El azúcar aporta contraste y la concentración evita que el vino quede eclipsado.", "El conjunto puede percibirse equilibrado si las intensidades son comparables.", "MC_SWEET_BALANCING_02", "Ignorar la interacción entre intensidad, sal y dulzor.", ["RA5", "maridaje", "queso azul", "vino dulce"], [FOOD_SOURCE]),
    _q("RA5", "sweet_service_temperature", "Si un Sauternes se sirve excesivamente frío, ¿qué consecuencia es más probable?", "Se atenúan aromas y textura, aunque el frío también reduce la sensación de dulzor.", ["Aumentan de inmediato los aromas de miel y roble.", "El azúcar precipita y el vino se vuelve seco.", "El alcohol sube por la baja temperatura."], "La temperatura de servicio es muy baja para un vino aromático y complejo.", "El frío reduce volatilidad aromática y percepción de cuerpo y dulzor.", "El vino puede parecer más cerrado y menos expresivo.", "MC_TEMPERATURE_INFLUENCE_01", "Creer que cuanto más frío, mejor para todo vino dulce.", ["RA5", "servicio", "Sauternes", "temperatura"], [SERVICE_SOURCE]),
    _q("RA5", "sweet_storage", "Si una botella de vino dulce de alta calidad se almacena de pie junto a una fuente de calor y luz, ¿qué resultado es más probable?", "El calor acelera el envejecimiento y la luz puede dañar aromas; el cierre también puede secarse si es corcho.", ["El azúcar protege por completo frente a calor y luz.", "La posición vertical mejora siempre la longevidad del corcho.", "La botella gana acidez y frescura con cada cambio térmico."], "La botella sufre temperatura alta, luz y posible desecación del cierre.", "Aumentan reacciones químicas y riesgo de entrada de oxígeno o pérdida de sellado.", "El vino puede evolucionar prematuramente y perder frescura.", "MC_AGEING_IMPROVEMENT_01", "Suponer que el azúcar hace indestructible un vino dulce.", ["RA5", "almacenamiento", "calor", "luz", "corcho"], [SERVICE_SOURCE]),
    _q("RA5", "sweet_open_bottle", "Si un restaurante quiere conservar una botella abierta de Tokaji durante varios días, ¿qué decisión explica mejor la práctica recomendada?", "Refrigerarla y limitar su contacto con oxígeno mediante un cierre eficaz.", ["Mantenerla abierta a temperatura ambiente para que respire.", "Agitarla cada día para reincorporar oxígeno.", "Exponerla a luz cálida para estabilizar el azúcar."], "Una botella abierta queda expuesta a oxígeno y microorganismos.", "Baja temperatura y buen cierre ralentizan oxidación y deterioro.", "El vino conserva mejor aromas y frescura durante el servicio posterior.", "MC_OXIDATIVE_VS_BIOLOGICAL_01", "Confundir aireación breve con almacenamiento abierto prolongado.", ["RA5", "servicio", "Tokaji", "botella abierta", "refrigeración"], [SERVICE_SOURCE]),
    _q("RA5", "sweet_portion_service", "Si se sirve un vino dulce muy concentrado después de una comida larga, ¿qué recomendación explica mejor una porción moderada?", "Su intensidad, dulzor y alcohol o cuerpo pueden fatigar el paladar en una medida grande.", ["Una porción pequeña impide percibir cualquier aroma.", "El azúcar se vuelve tóxico al superar media copa.", "La medida de servicio cambia la acidez química del vino."], "El vino posee alta concentración y gran impacto sensorial.", "Una cantidad moderada permite apreciar complejidad sin saturar el paladar.", "Mejora la experiencia de servicio y el equilibrio con el plato.", "MC_SWEET_BALANCING_02", "Tratar todos los vinos como si exigieran la misma medida.", ["RA5", "servicio", "vino dulce", "porción"], [SERVICE_SOURCE]),
    _q("RA5", "sweet_pairing_acid", "Si un postre de fruta tiene dulzor alto y acidez marcada, ¿qué recomendación de vino es más probable que mantenga el equilibrio?", "Un vino al menos tan dulce como el postre y con acidez suficiente para acompañar su frescura.", ["Un tinto muy tánico y menos dulce que el postre.", "Un vino plano y de acidez baja para evitar contraste.", "Cualquier vino seco, porque la fruta reduce la percepción de acidez."], "El plato combina azúcar y una línea ácida perceptible.", "El vino necesita dulzor para no parecer austero y acidez para no quedar pesado.", "Un estilo dulce y fresco conserva armonía con el postre.", "MC_SWEET_BALANCING_02", "Elegir por dulzor sin considerar acidez e intensidad.", ["RA5", "maridaje", "postre de fruta", "acidez"], [FOOD_SOURCE]),
]


BATCH_2 = [
    _q("RA4", "port_early_fortification", "Si un productor de Port añade aguardiente antes de que la levadura consuma la mayor parte del azúcar, ¿qué resultado es más probable?", "La fermentación se detiene y el vino conserva azúcar residual con alcohol elevado.", ["La fermentación acelera hasta sequedad.", "El vino pierde color porque el alcohol impide toda extracción previa.", "El azúcar se transforma en acidez volátil."], "El mosto tinto está fermentando cuando se añade aguardiente.", "El aumento brusco de alcohol inhibe o mata la levadura.", "Quedan azúcar residual y un grado alcohólico final alto.", "MC_PORT_FORTIFICATION_02", "Confundir fortificación temprana con simple aumento de alcohol.", ["Port", "fortificación", "fermentación", "azúcar residual"], [PORT_SOURCE]),
    _q("RA4", "port_extraction_speed", "Si la fermentación de Port dura solo unas 24 a 36 horas antes de fortificar, ¿qué decisión explica mejor la necesidad de extracción intensa?", "Usar pisado o sistemas mecánicos vigorosos para obtener color y tanino rápidamente.", ["Reducir todo contacto con hollejos hasta después de fortificar.", "Fermentar a baja temperatura durante varias semanas.", "Filtrar el mosto antes de iniciar la fermentación."], "La fortificación interrumpe pronto una fermentación tinta corta.", "Hay poco tiempo para extraer pigmentos y taninos de los hollejos.", "Se requieren técnicas intensas para lograr estructura y color suficientes.", "MC_PORT_FORTIFICATION_02", "Ignorar cómo el momento de fortificación limita la extracción.", ["Port", "extracción", "lagares", "fermentación corta"], [PORT_SOURCE]),
    _q("RA4", "port_fortification_timing_sweetness", "Dos lotes de Port parten del mismo mosto; uno se fortifica antes. ¿Qué consecuencia es más probable?", "El lote fortificado antes conservará más azúcar residual.", ["El lote fortificado antes será necesariamente más tánico.", "Ambos tendrán idéntico dulzor porque el aguardiente contiene azúcar.", "El lote tardío tendrá siempre menos alcohol final."], "Los lotes fermentan el mismo azúcar durante tiempos distintos.", "La fortificación temprana detiene antes el consumo de azúcar por la levadura.", "El momento de adición ayuda a definir el dulzor del estilo.", "MC_FORTIFICATION_TIMING_01", "Creer que el dulzor de Port no depende del momento de fortificación.", ["Port", "momento de fortificación", "dulzor", "azúcar residual"], [PORT_SOURCE]),
    _q("RA4", "port_ruby_maturation", "Si un Port madura poco tiempo en recipientes grandes con escaso efecto del oxígeno, ¿qué resultado de estilo es más probable?", "Color profundo y predominio de fruta primaria, propio de la familia ruby.", ["Color marrón y notas dominantes de nuez y caramelo.", "Carácter de flor, masa de pan y acetaldehído.", "Pérdida completa de tanino antes del embotellado."], "El vino se mantiene en un gran volumen con baja relación superficie-volumen.", "Se limita la exposición oxidativa durante la maduración.", "Se preservan color y fruta primaria intensa.", "MC_PORT_VINTAGE_01", "Confundir todo Port envejecido con estilo tawny.", ["Port", "ruby", "recipiente grande", "fruta primaria"], [PORT_SOURCE]),
    _q("RA4", "port_tawny_maturation", "Si un Port envejece durante años en pipes con exposición gradual al oxígeno, ¿qué resultado es más probable?", "Pierde color y fruta fresca mientras desarrolla nuez, café, caramelo y frutos secos.", ["Conserva un perfil exclusivamente de fruta negra fresca.", "Forma flor protectora y permanece pálido.", "Aumenta su presión de dióxido de carbono."], "El vino madura largo tiempo en recipientes de madera relativamente pequeños.", "El contacto con oxígeno transforma pigmentos y aromas primarios.", "El estilo evoluciona hacia color tawny y complejidad oxidativa.", "MC_PORT_VINTAGE_01", "Confundir tawny auténtico con un ruby de color aclarado.", ["Port", "tawny", "oxidación", "pipes"], [PORT_SOURCE]),
    _q("RA4", "port_vintage_bottle_ageing", "Si un Vintage Port se embotella joven sin filtrar, ¿qué consecuencia es más probable durante décadas de guarda?", "Desarrolla aromas terciarios, suaviza taninos y forma abundante sedimento.", ["Se mantiene idéntico porque el alto alcohol detiene toda evolución.", "Se vuelve tawny por oxidación intensa en barrica.", "Pierde todo color en el primer año."], "El vino concentrado y tánico entra joven en botella con materia sólida.", "La evolución reductiva integra estructura y precipita pigmentos y taninos.", "Aparecen complejidad terciaria y sedimento que puede exigir decantación.", "MC_PORT_VINTAGE_01", "Creer que Vintage Port está listo y estable al embotellarse.", ["Vintage Port", "botella", "tanino", "sedimento"], [PORT_SOURCE]),
    _q("RA4", "port_lbv_filtered", "Al comparar un LBV filtrado con uno sin filtrar, ¿qué resultado explica mejor la diferencia de servicio y evolución?", "El filtrado suele estar listo al salir y forma poco sedimento; el no filtrado puede evolucionar y requerir decantación.", ["El filtrado siempre tiene más tanino y necesita décadas.", "El no filtrado no puede proceder de una sola añada.", "La filtración convierte un ruby en tawny."], "Los dos vinos reciben distinto tratamiento antes del embotellado.", "Filtrar retira partículas y reduce el material que precipitaría en botella.", "Cambian el potencial de guarda y la necesidad de decantar.", "MC_PORT_VINTAGE_01", "Tratar todos los LBV como un único estilo de servicio.", ["Port", "LBV", "filtración", "decantación"], [PORT_SOURCE]),
    _q("RA4", "port_tawny_age_label", "Si una botella de Tawny indica 20 años, ¿qué interpretación explica mejor el estilo esperado?", "Es una mezcla cuyo carácter corresponde a una edad media aproximada, no vino íntegramente de una sola cosecha de 20 años.", ["Todo el vino procede exactamente de una añada de hace 20 años.", "El componente más joven debe tener 20 años.", "La cifra indica años de botella después de la compra."], "El productor mezcla vinos de distintas edades durante la maduración oxidativa.", "La categoría expresa el perfil típico de una edad media aprobada.", "El vino busca consistencia y complejidad, no identidad de una sola añada.", "MC_PORT_VINTAGE_01", "Leer la indicación de edad como una añada literal.", ["Port", "Tawny", "indicación de edad", "mezcla"], [PORT_SOURCE]),
    _q("RA4", "port_vintage_vs_tawny", "Al comparar Vintage Port madurado en botella y Tawny con indicación de edad madurado en madera, ¿qué factor explica mejor sus perfiles distintos?", "El primero limita oxígeno antes de botella; el segundo recibe larga maduración oxidativa en pipes.", ["La única diferencia es la variedad de uva.", "Vintage se fortifica y Tawny no.", "Tawny desarrolla flor mientras Vintage envejece bajo velo."], "Ambos parten de Port tinto fortificado, pero siguen recipientes y tiempos distintos.", "La botella protege más del oxígeno; las pipes favorecen oxidación gradual.", "Vintage conserva y transforma fruta y tanino; Tawny desarrolla carácter oxidativo y está listo al embotellar.", "MC_PORT_VINTAGE_01", "Confundir estilo de maduración con nivel de calidad.", ["Port", "Vintage", "Tawny", "maduración"], [PORT_SOURCE]),
    _q("RA4", "port_gaia_climate", "Si un Port madura en el ambiente costero más fresco de Vila Nova de Gaia en lugar de condiciones más cálidas del Douro, ¿qué consecuencia es más probable?", "La evolución será más lenta y se preservará mejor la frescura.", ["El vino se oxidará más rápido por la menor temperatura.", "La fermentación reiniciará necesariamente.", "El aguardiente se separará del vino."], "El vino se almacena en un entorno más fresco y moderado.", "La temperatura menor ralentiza reacciones de envejecimiento.", "La maduración puede ser más gradual y controlada.", "MC_PORT_VINTAGE_01", "Ignorar el efecto de la temperatura de almacenamiento en Port.", ["Port", "Vila Nova de Gaia", "temperatura", "maduración"], [PORT_SOURCE]),
    _q("RA4", "sherry_first_classification", "Si un vino base de Palomino es pálido, ligero y fino tras la fermentación, ¿qué decisión explica mejor su destino inicial?", "Fortificarlo cerca de 15 a 15,5% para favorecer flor y crianza biológica.", ["Fortificarlo de inmediato a 22% para crear PX.", "Endulzarlo antes de que aparezca flor.", "Concentrarlo por congelación."], "El productor clasifica el vino según su cuerpo y finura.", "Un grado cercano a 15% permite que la flor prospere.", "El vino puede desarrollar un estilo Fino o Manzanilla protegido del oxígeno.", "MC_SHERRY_FLOR_01", "Creer que la clasificación inicial es aleatoria.", ["Sherry", "clasificación", "flor", "15.5%"], [SHERRY_SOURCE]),
    _q("RA4", "sherry_oloroso_fortification", "Si un vino base más robusto se fortifica a 17% antes de la crianza, ¿qué resultado es más probable?", "La flor no sobrevive y el vino inicia crianza oxidativa hacia Oloroso.", ["La flor crece más gruesa y protege el vino.", "El vino se vuelve espumoso.", "La fortificación elimina todo cuerpo y color."], "El vino recibe una graduación superior al límite de tolerancia de la flor.", "Sin velo protector, el oxígeno actúa en la bota parcialmente llena.", "Se desarrollan color más oscuro, cuerpo y aromas de nuez, cuero y toffee.", "MC_SHERRY_FLOR_01", "Pensar que más alcohol fortalece la flor.", ["Sherry", "Oloroso", "17%", "oxidativa"], [SHERRY_SOURCE]),
    _q("RA4", "sherry_flor_protection", "Si una capa sana de flor cubre un Fino, ¿qué consecuencia explica mejor que conserve color pálido durante la crianza?", "La flor consume oxígeno y forma una barrera que limita la oxidación del vino.", ["La flor añade pigmentos blancos al vino.", "El alto tanino impide el oscurecimiento.", "La bota se llena por completo y no contiene aire."], "Levaduras de flor crecen sobre el vino en una bota parcialmente llena.", "La capa utiliza oxígeno y reduce el contacto oxidativo directo.", "El vino permanece pálido y desarrolla acetaldehído, almendra y notas de masa.", "MC_BIOLOGICAL_PROTECTION_02", "Creer que una bota parcialmente llena siempre oxida el vino por igual.", ["Sherry", "Fino", "flor", "protección"], [SHERRY_SOURCE]),
    _q("RA4", "sherry_flor_conditions", "Si una bodega se vuelve demasiado cálida y seca durante la crianza de Fino, ¿qué consecuencia es más probable?", "La flor se debilita y aumenta el riesgo de desarrollo oxidativo.", ["La flor crece más vigorosa cuanto más calor y sequedad.", "El vino pierde alcohol hasta quedar sin protección.", "La solera deja de mezclar edades."], "La flor necesita un rango adecuado de alcohol, temperatura y humedad.", "Condiciones adversas reducen su actividad y continuidad.", "Disminuyen la protección y el carácter biológico.", "MC_SHERRY_FLOR_01", "Suponer que la flor prospera en cualquier ambiente.", ["Sherry", "flor", "temperatura", "humedad"], [SHERRY_SOURCE]),
    _q("RA4", "sherry_solera_consistency", "Si una solera se refresca periódicamente con vinos más jóvenes bien seleccionados, ¿qué resultado explica mejor su consistencia?", "Cada saca mezcla edades y el vino joven adopta gradualmente el carácter del sistema.", ["Cada botella conserva una única añada identificable.", "El vino joven reemplaza por completo al viejo en cada movimiento.", "La mezcla impide cualquier envejecimiento."], "Se extrae solo una fracción del nivel más viejo y se repone desde criaderas.", "El ensamblaje repetido integra vinos de diferentes edades.", "La casa mantiene un perfil relativamente estable entre embotellados.", "MC_SHERRY_SOLERA_02", "Confundir solera con un sistema de añadas separadas.", ["Sherry", "solera", "criaderas", "consistencia"], [SHERRY_SOURCE]),
    _q("RA4", "sherry_solera_overdraw", "Si un productor extrae demasiado vino de una solera cada año, ¿qué consecuencia es más probable?", "Se reduce la edad media y puede diluirse el carácter maduro del sistema.", ["La edad media aumenta automáticamente.", "La flor se convierte en azúcar.", "El vino deja de mezclarse con componentes jóvenes."], "La saca retira una proporción excesiva del vino viejo.", "La reposición introduce relativamente más vino joven en cada ciclo.", "Puede perderse concentración, continuidad y consistencia.", "MC_SHERRY_SOLERA_02", "Suponer que el volumen extraído no afecta la solera.", ["Sherry", "solera", "saca", "edad media"], [SHERRY_SOURCE]),
    _q("RA4", "sherry_amontillado_transition", "Si un Fino se refortifica a 17% después de una etapa biológica, ¿qué resultado de estilo es más probable?", "La flor muere y el vino añade notas oxidativas a su carácter previo de levadura y almendra.", ["La refortificación reinicia una flor más gruesa.", "El vino pierde todo rastro de crianza biológica.", "El estilo se convierte en PX naturalmente dulce."], "El vino ya ha desarrollado carácter bajo flor.", "La nueva fortificación elimina la flor y expone el vino a oxígeno.", "Amontillado combina señales biológicas y oxidativas.", "MC_OXIDATIVE_VS_BIOLOGICAL_01", "Tratar Amontillado como exclusivamente biológico u oxidativo.", ["Sherry", "Amontillado", "refortificación", "crianza mixta"], [SHERRY_SOURCE]),
    _q("RA4", "sherry_oloroso_style", "Si un Sherry envejece exclusivamente sin flor en botas parcialmente llenas, ¿qué resultado es más probable?", "Un Oloroso de color oscuro, cuerpo pleno y aromas de nuez, cuero, especias y toffee.", ["Un Fino pálido con masa de pan.", "Un vino de fruta floral primaria sin evolución.", "Un espumoso de alta acidez."], "El vino fortificado a 17% madura con aire en la bota.", "La oxidación prolongada transforma color y compuestos aromáticos.", "Aumentan riqueza, concentración y carácter terciario oxidativo.", "MC_OXIDATIVE_VS_BIOLOGICAL_01", "Confundir Oloroso con un vino biológico.", ["Sherry", "Oloroso", "oxidación", "nuez"], [SHERRY_SOURCE]),
    _q("RA4", "sherry_manzanilla", "Si un vino criado bajo flor madura en el ambiente costero fresco y húmedo de Sanlúcar, ¿qué resultado es más probable frente a un Fino interior?", "Una flor más constante y un perfil especialmente fresco, tangy y salino.", ["Una crianza exclusivamente oxidativa por la humedad.", "Mayor color por desaparición inmediata de la flor.", "Un vino dulce por concentración costera."], "Sanlúcar ofrece condiciones frescas y húmedas favorables a la flor.", "La capa puede mantenerse gruesa y activa durante más tiempo.", "Manzanilla intensifica el carácter biológico y la frescura.", "MC_SHERRY_FLOR_01", "Creer que costa y humedad impiden la flor.", ["Sherry", "Manzanilla", "Sanlúcar", "flor"], [SHERRY_SOURCE]),
    _q("RA4", "sherry_px_drying", "Si las uvas PX se secan al sol antes de fermentar, ¿qué resultado explica mejor el estilo posterior?", "El agua se evapora, el mosto se concentra y la fermentación alcanza poco alcohol antes de fortificar.", ["El secado reduce el azúcar y facilita fermentar hasta sequedad.", "Las uvas forman flor antes del prensado.", "El vino adquiere tanino alto de piel tinta."], "Las bayas de PX pierden agua bajo el sol.", "El jugo concentrado crea fuerte presión osmótica para la levadura.", "El vino conserva enorme azúcar residual y carácter de pasas.", "MC_SWEET_CONCENTRATION_01", "Confundir secado con fermentación completa.", ["Sherry", "PX", "secado al sol", "azúcar residual"], [SHERRY_SOURCE]),
    _q("RA4", "sherry_en_rama", "Si un Fino se embotella en rama con mínima clarificación y filtración, ¿qué consecuencia de estilo es más probable?", "Puede conservar mayor intensidad y textura, pero exige manejo cuidadoso de estabilidad y frescura.", ["Se vuelve oxidativo antes de salir de bodega por definición.", "Pierde todo carácter de flor.", "No puede contener partículas ni variación."], "El productor reduce intervenciones que retirarían parte del material del vino.", "Se conserva más carácter del vino de bota junto con mayor sensibilidad.", "El estilo puede ser más expresivo y menos estandarizado.", "MC_SHERRY_FLOR_01", "Suponer que más filtración siempre mejora un Fino.", ["Sherry", "en rama", "filtración", "intensidad"], [SHERRY_SOURCE]),
    _q("RA4", "sherry_fino_freshness", "Si una botella de Fino permanece abierta o guardada demasiado tiempo, ¿qué consecuencia es más probable?", "Pierde frescura biológica y desarrolla oxidación no deseada.", ["Mejora indefinidamente porque la flor sigue viva en botella.", "Aumenta su azúcar residual.", "Se convierte en Vintage Port."], "El Fino ya no está protegido por una cultura activa de flor en la botella.", "El oxígeno del cierre abierto o el tiempo degrada sus aromas delicados.", "Disminuyen frescura, almendra y notas de masa.", "MC_OXIDATIVE_VS_BIOLOGICAL_01", "Creer que Fino mejora con larga guarda en botella.", ["Sherry", "Fino", "frescura", "botella abierta"], [SHERRY_SOURCE]),
    _q("RA4", "madeira_heat_ageing", "Si un Madeira madura con calor y oxígeno mediante estufagem, ¿qué resultado es más probable?", "Desarrolla rápidamente notas de caramelo, frutos secos y tostado con gran estabilidad posterior.", ["Conserva solo fruta primaria delicada.", "Forma flor y permanece pálido.", "Pierde toda acidez por efecto del calor."], "El vino fortificado se expone deliberadamente a calor y oxígeno.", "Se aceleran reacciones oxidativas y de calentamiento.", "Aparece un perfil desarrollado y resistente a oxidación posterior.", "MC_MADEIRA_OXIDATION_01", "Tratar el calor como defecto accidental en todo Madeira.", ["Madeira", "estufagem", "calor", "oxidación"], [MADEIRA_SOURCE, MATURATION_SOURCE]),
    _q("RA4", "madeira_canteiro", "Al comparar canteiro con estufagem, ¿qué factor explica mejor que canteiro pueda dar un estilo más fino y complejo?", "El calentamiento natural es más lento y prolongado, permitiendo una evolución gradual.", ["Canteiro elimina por completo el oxígeno.", "Estufagem siempre usa flor.", "Canteiro congela el vino antes de madurarlo."], "El vino en canteiro envejece en madera en zonas cálidas sin calentamiento rápido de tanque.", "La energía térmica actúa de forma más suave durante años.", "La complejidad se desarrolla con mayor lentitud e integración.", "MC_MADEIRA_OXIDATION_01", "Suponer que ambos métodos de calentamiento producen idéntico resultado.", ["Madeira", "canteiro", "estufagem", "complejidad"], [MADEIRA_SOURCE]),
    _q("RA4", "madeira_acidity", "Si un Madeira dulce conserva acidez muy alta después de la maduración con calor, ¿qué consecuencia sensorial es más probable?", "El dulzor queda equilibrado y el vino mantiene frescura pese a su carácter desarrollado.", ["La acidez alta impide cualquier percepción de dulzor.", "El calor convierte la acidez en tanino.", "El vino debe percibirse ligero y neutro."], "El vino combina azúcar residual con una base ácida marcada.", "La acidez contrasta la riqueza y sostiene el final.", "Incluso estilos dulces pueden resultar tensos y longevos.", "MC_MADEIRA_SWEETNESS_02", "Creer que Madeira dulce es necesariamente pesado.", ["Madeira", "acidez", "dulzor", "equilibrio"], [MADEIRA_SOURCE]),
    _q("RA4", "madeira_fortification_timing", "Dos Madeiras parten del mismo mosto; uno se fortifica antes durante la fermentación. ¿Qué consecuencia es más probable?", "El fortificado antes conservará más azúcar residual.", ["El fortificado antes será automáticamente más oxidativo.", "Ambos quedarán igual de secos.", "El momento solo cambia el color, no el dulzor."], "La levadura consume azúcar hasta que el alcohol añadido detiene su actividad.", "Una interrupción temprana deja más azúcar sin fermentar.", "El productor puede definir estilos de distinto dulzor.", "MC_FORTIFICATION_TIMING_01", "Ignorar el vínculo entre fortificación y dulzor de Madeira.", ["Madeira", "fortificación", "dulzor", "fermentación"], [MADEIRA_SOURCE]),
    _q("RA4", "madeira_oxidative_stability", "Si una botella abierta de Madeira conserva bien su estilo durante más tiempo que muchos vinos tranquilos, ¿qué factor explica mejor esa resistencia?", "Ya ha sido expuesta a calor, oxígeno y fortificación durante su elaboración.", ["No contiene agua que pueda oxidarse.", "La flor sigue protegiéndola en botella.", "El azúcar impide toda reacción química."], "El vino se estabiliza mediante alcohol elevado y maduración oxidativa térmica.", "Muchos cambios que dañarían un vino delicado ya forman parte de su estilo.", "Tolera mejor una exposición posterior moderada al oxígeno.", "MC_MADEIRA_OXIDATION_01", "Creer que Madeira es estable solo por el azúcar.", ["Madeira", "estabilidad", "calor", "oxígeno"], [MADEIRA_SOURCE]),
    _q("RA4", "madeira_colour_aroma", "Si un Madeira envejece durante años con calor y oxígeno, ¿qué resultado visual y aromático es más probable?", "Color más profundo con frutos secos, caramelo, piel de cítricos y especias.", ["Color más pálido y fruta verde primaria.", "Burbuja fina y autólisis.", "Aromas herbáceos de fermentación fría."], "Pigmentos y aromas reaccionan durante maduración oxidativa caliente.", "El tiempo y la temperatura transforman compuestos primarios.", "El vino adquiere color y complejidad desarrollados.", "MC_MADEIRA_OXIDATION_01", "Esperar que Madeira conserve un perfil juvenil.", ["Madeira", "color", "caramelo", "frutos secos"], [MADEIRA_SOURCE]),
    _q("RA4", "madeira_quality_method", "Dos Madeiras muestran igual dulzor; uno tiene mayor acidez, longitud e integración del carácter térmico. ¿Qué factor explica mejor su mayor calidad?", "El equilibrio y la complejidad integrada importan más que el dulzor aislado.", ["El vino más dulce siempre es superior.", "Más calor siempre produce mayor calidad.", "La acidez alta es un defecto en vinos fortificados."], "La calidad depende de estructura, concentración, complejidad y persistencia.", "La acidez y la integración evitan que calor y azúcar dominen.", "El vino resulta más equilibrado y largo.", "MC_MADEIRA_SWEETNESS_02", "Equiparar dulzor o calentamiento con calidad.", ["Madeira", "calidad", "equilibrio", "longitud"], [MADEIRA_SOURCE]),
    _q("RA4", "madeira_vs_tawny", "Al comparar Madeira y Tawny Port, ¿qué factor explica mejor que ambos muestren frutos secos pero Madeira conserve una acidez más incisiva?", "Madeira combina maduración oxidativa con una base naturalmente muy ácida y exposición térmica.", ["Tawny no recibe oxígeno durante la crianza.", "Madeira se cría bajo flor.", "Port se elabora sin fortificación."], "Ambos estilos evolucionan con oxígeno, pero parten de matrices distintas.", "El origen y el proceso térmico de Madeira mantienen una firma ácida particular.", "Comparten notas desarrolladas sin ser estilos equivalentes.", "MC_MADEIRA_SWEETNESS_02", "Tratar todos los fortificados oxidativos como intercambiables.", ["Madeira", "Tawny Port", "oxidación", "acidez"], [MADEIRA_SOURCE, PORT_SOURCE]),
    _q("RA4", "muscat_youthful_aroma", "Si un Muscat fortificado busca un estilo juvenil y floral, ¿qué decisión explica mejor su elaboración?", "Fermentación fresca, fortificación para conservar azúcar y protección del oxígeno en recipiente inerte.", ["Larga crianza cálida en madera nueva.", "Secado extremo que enmascare el aroma varietal.", "Crianza bajo flor durante décadas."], "La uva posee aromas intensos de flor, rosa y uva fresca.", "Baja temperatura, fortificación y almacenamiento inerte reducen pérdida y oxidación aromática.", "El vino conserva perfume primario y dulzor fresco.", "MC_FORTIFICATION_TIMING_01", "Confundir Muscat juvenil con Muscat oxidativo envejecido.", ["Muscat", "juvenil", "aromas florales", "fortificación"], [MUSCAT_SOURCE]),
    _q("RA4", "muscat_skin_contact", "Si un productor prolonga moderadamente el contacto con pieles en un Muscat fortificado juvenil, ¿qué resultado es más probable?", "Aumentan intensidad aromática y riqueza de textura.", ["Desaparecen todos los aromas varietales.", "Se forma un tanino comparable al de Vintage Port.", "El vino se vuelve oxidativo por definición."], "Muchos compuestos aromáticos se concentran en las pieles de Muscat.", "El contacto permite extraerlos al mosto o vino en fermentación.", "El estilo gana perfume y cuerpo si la extracción se controla.", "MC_FORTIFICATION_TIMING_01", "Suponer que todo contacto con pieles busca tanino alto.", ["Muscat", "contacto con pieles", "aroma", "textura"], [MUSCAT_SOURCE]),
    _q("RA4", "muscat_raisining", "Si las uvas para un Rutherglen Muscat muy dulce se dejan raisinar parcialmente antes de cosechar, ¿qué consecuencia es más probable?", "Aumentan concentración y notas de fruta seca, pero un exceso puede reducir el perfume varietal.", ["El secado intensifica indefinidamente la flor fresca sin riesgo.", "La uva pierde azúcar mientras gana agua.", "El método obliga a fermentar hasta sequedad."], "La fruta pierde agua y avanza hacia pasificación.", "Se concentran azúcar y sabores, mientras los aromas frescos pueden degradarse.", "El productor equilibra riqueza con conservación del carácter Muscat.", "MC_MADEIRA_SWEETNESS_02", "Creer que más pasificación siempre mejora Muscat.", ["Rutherglen Muscat", "raisining", "concentración", "aroma varietal"], [MUSCAT_SOURCE]),
    _q("RA4", "muscat_early_fortification", "Si un Rutherglen Muscat se fortifica cuando la fermentación apenas alcanza alrededor de 2% de alcohol, ¿qué resultado es más probable?", "Conserva una cantidad muy alta de azúcar residual y queda en estilo luscious.", ["Termina seco porque el aguardiente alimenta la levadura.", "Pierde todo aroma de uva por falta de alcohol.", "Se vuelve biológico bajo flor."], "La fermentación ha consumido muy poco azúcar cuando llega el alcohol añadido.", "La levadura se detiene antes de transformar la mayor parte del azúcar.", "El vino queda muy dulce, rico y fortificado.", "MC_FORTIFICATION_TIMING_01", "Creer que una fortificación muy temprana produce más alcohol fermentativo.", ["Rutherglen Muscat", "fortificación temprana", "luscious", "azúcar residual"], [MUSCAT_SOURCE]),
    _q("RA4", "muscat_old_oak", "Si un Rutherglen Muscat envejece durante décadas, ¿qué factor explica mejor el uso de madera vieja en vez de roble nuevo?", "La madera vieja permite oxígeno sin aromas nuevos que compitan con el carácter Muscat.", ["El roble viejo impide toda oxidación.", "La madera nueva eliminaría el alcohol.", "El roble viejo crea flor."], "El vino necesita maduración oxidativa prolongada, pero posee aromas varietales intensos.", "Recipientes viejos transmiten poco sabor de madera y permiten intercambio de oxígeno.", "Se desarrollan complejidad y concentración sin dominar el perfume de Muscat.", "MC_OAK_QUALITY_01", "Suponer que roble nuevo siempre mejora un fortificado.", ["Rutherglen Muscat", "madera vieja", "oxidación", "aroma"], [MUSCAT_SOURCE]),
    _q("RA4", "muscat_warm_ageing", "Si un Muscat fortificado envejece en condiciones cálidas y oxidativas, ¿qué resultado es más probable?", "Evoluciona de ámbar a marrón y desarrolla caramelo, frutos secos y fruta deshidratada.", ["Conserva únicamente flor de azahar fresca.", "Se vuelve pálido por protección de flor.", "Desarrolla burbujas por el calor."], "El vino dulce fortificado recibe calor y oxígeno durante años.", "Se aceleran oxidación, evaporación y transformación aromática.", "Aumentan concentración, color y complejidad desarrollada.", "MC_OXIDATIVE_VS_BIOLOGICAL_01", "Confundir oxidación controlada con defecto simple.", ["Rutherglen Muscat", "calor", "oxidación", "color marrón"], [MUSCAT_SOURCE]),
    _q("RA4", "muscat_young_blend", "Si una pequeña proporción de Muscat joven se mezcla en un vino muy viejo antes de embotellar, ¿qué resultado explica mejor la decisión?", "Aporta un levantamiento aromático floral sin borrar la complejidad oxidativa.", ["Reduce el alcohol hasta convertirlo en vino tranquilo.", "Elimina todo azúcar residual del vino viejo.", "Crea una segunda fermentación obligatoria."], "El vino viejo puede ser muy concentrado y dominado por aromas desarrollados.", "Una fracción joven aporta compuestos varietales más volátiles.", "El ensamblaje recupera perfume y equilibrio.", "MC_AGEING_IMPROVEMENT_01", "Creer que el componente más viejo siempre debe ser el único.", ["Rutherglen Muscat", "mezcla", "vino joven", "aroma"], [MUSCAT_SOURCE]),
    _q("RA4", "muscat_cooling_influence", "Si un viñedo cálido de Muscat recibe una influencia refrescante, ¿qué consecuencia es más probable para un fortificado de calidad?", "Conserva mejor acidez y aromas florales durante la maduración.", ["Aumenta automáticamente el raisining extremo.", "La fruta pierde todo azúcar.", "El vino desarrolla más tanino de piel."], "Muscat prospera en clima cálido pero sus aromas y acidez son sensibles al exceso de calor.", "La moderación térmica ralentiza pérdidas de ácido y compuestos volátiles.", "El vino puede combinar madurez, perfume y equilibrio.", "MC_COOL_CLIMATE_01", "Suponer que más calor siempre mejora Muscat.", ["Muscat", "Rutherglen", "influencia refrescante", "acidez"], [MUSCAT_SOURCE]),
    _q("RA4", "muscat_young_vs_aged", "Al comparar un Muscat fortificado juvenil con uno envejecido, ¿qué factor explica mejor sus perfiles opuestos?", "El juvenil evita oxígeno para conservar flores y uva; el envejecido usa calor y oxígeno para desarrollar frutos secos y caramelo.", ["Uno se fortifica y el otro no.", "El juvenil debe ser seco y el viejo siempre dulce.", "La única diferencia es el color de la botella."], "Los estilos parten de la misma familia aromática con objetivos de maduración distintos.", "El control o la búsqueda de oxígeno dirige la evolución aromática.", "Se obtienen perfiles frescos o plenamente desarrollados.", "MC_OXIDATIVE_VS_BIOLOGICAL_01", "Confundir edad con una simple escala de calidad.", ["Muscat", "juvenil", "envejecido", "oxidación"], [MUSCAT_SOURCE]),
    _q("RA4", "fortification_port_vs_sherry", "Al comparar Port y Fino Sherry, ¿qué factor explica mejor que Port sea dulce y Fino seco?", "Port se fortifica durante la fermentación; Fino se fortifica después de fermentar hasta sequedad.", ["Fino no contiene alcohol añadido.", "Port se endulza solo después de embotellar.", "La flor convierte el azúcar de Port en alcohol."], "Los dos vinos reciben alcohol en momentos diferentes.", "La fortificación temprana deja azúcar; la tardía modifica un vino ya seco.", "El momento de adición determina estilos estructuralmente distintos.", "MC_FORTIFICATION_TIMING_01", "Tratar toda fortificación como el mismo proceso.", ["Port", "Fino", "fortificación", "dulzor"], [PORT_SOURCE, SHERRY_SOURCE]),
    _q("RA4", "biological_vs_oxidative", "Al comparar Fino y Oloroso, ¿qué factor explica mejor sus diferencias de color y aroma?", "La flor protege al Fino; Oloroso envejece expuesto al oxígeno sin flor.", ["Fino usa uvas tintas y Oloroso blancas.", "Oloroso no se fortifica.", "Fino envejece en barricas completamente llenas."], "La graduación inicial determina si la flor puede sobrevivir.", "Con flor se limita oxidación; sin flor el aire transforma el vino.", "Fino queda pálido y punzante; Oloroso se vuelve oscuro, rico y nuez.", "MC_OXIDATIVE_VS_BIOLOGICAL_01", "Confundir el nivel de llenado con la presencia efectiva de protección.", ["Fino", "Oloroso", "biológica", "oxidativa"], [SHERRY_SOURCE]),
    _q("RA4", "oxidative_style_comparison", "Al comparar Oloroso, Tawny Port y Madeira, ¿qué factor explica mejor que compartan notas de nuez pero no sepan iguales?", "Todos reciben oxidación, pero difieren en vino base, dulzor, fortificación, recipiente, temperatura y tiempo.", ["La oxidación borra todas las diferencias de origen.", "Los tres se crían bajo flor.", "Los tres se fortifican en el mismo punto de fermentación."], "Varios fortificados pueden usar oxígeno como herramienta de maduración.", "La matriz inicial y las condiciones específicas modifican las reacciones.", "Surgen familias aromáticas comunes junto con estructuras y firmas distintas.", "MC_OXIDATIVE_VS_BIOLOGICAL_01", "Tratar oxidativo como un único estilo uniforme.", ["Oloroso", "Tawny Port", "Madeira", "comparación"], [SHERRY_SOURCE, PORT_SOURCE, MADEIRA_SOURCE]),
    _q("RA4", "fortification_volume", "Si un vino se fortifica cuando aún tiene alcohol fermentativo muy bajo, ¿qué consecuencia es más probable respecto al volumen de aguardiente necesario?", "Se necesita una proporción mayor de aguardiente para alcanzar el alcohol final objetivo.", ["Se necesita menos porque el azúcar cuenta como alcohol.", "No hace falta aguardiente si el vino es dulce.", "El volumen añadido depende solo del color."], "El vino base aporta poco alcohol antes de fortificar.", "Más alcohol externo debe cubrir la diferencia hasta el grado final.", "El aguardiente representa una parte mayor del volumen terminado.", "MC_FORTIFICATION_TIMING_01", "Ignorar el alcohol inicial al comparar fortificación.", ["fortificación", "aguardiente", "alcohol inicial", "volumen"], [PORT_SOURCE, MUSCAT_SOURCE]),
    _q("RA4", "fortification_extraction", "Si un tinto fortificado interrumpe su fermentación muy pronto, ¿qué decisión explica mejor cómo conservar estructura suficiente?", "Aumentar la extracción antes de fortificar mediante contacto intenso con hollejos.", ["Esperar a extraer color después de filtrar las pieles.", "Evitar todo movimiento del sombrero.", "Usar exclusivamente crianza en botella para crear tanino."], "La extracción de color y tanino ocurre durante contacto con pieles.", "La fermentación corta limita el tiempo disponible.", "Una técnica más intensa compensa la ventana breve.", "MC_PORT_FORTIFICATION_02", "Separar fortificación temprana de la estrategia de extracción.", ["fortificación", "extracción", "hollejos", "estructura"], [PORT_SOURCE]),
    _q("RA4", "ageing_vessel_comparison", "Al comparar un gran tonel con una pipe pequeña para madurar Port, ¿qué factor explica mejor la diferencia de evolución?", "La pipe ofrece mayor relación superficie-volumen y favorece una oxidación más rápida.", ["El tonel grande siempre aporta más roble nuevo.", "La pipe impide evaporación.", "El tamaño no cambia el contacto con oxígeno."], "Los recipientes contienen volúmenes distintos para una superficie de contacto dada.", "El recipiente pequeño expone proporcionalmente más vino a madera y oxígeno.", "La evolución hacia carácter tawny se acelera.", "MC_PORT_VINTAGE_01", "Ignorar el efecto del tamaño de recipiente.", ["Port", "pipe", "tonel", "superficie-volumen"], [PORT_SOURCE]),
    _q("RA4", "old_oak_comparison", "¿Qué factor explica mejor que Port, Sherry y Rutherglen Muscat usen con frecuencia madera vieja?", "Buscan intercambio de oxígeno o almacenamiento sin que sabores de roble nuevo dominen el estilo.", ["La madera vieja añade más vainilla que la nueva.", "El roble viejo impide toda evaporación.", "Los reglamentos exigen el mismo tamaño de barrica."], "Los vinos poseen perfiles varietales o de crianza propios.", "Recipientes usados permiten evolución con poca cesión aromática de madera.", "El carácter de fruta, flor u oxidación permanece en primer plano.", "MC_OAK_QUALITY_01", "Asumir que madera nueva es siempre superior.", ["Port", "Sherry", "Rutherglen Muscat", "madera vieja"], [PORT_SOURCE, SHERRY_SOURCE, MUSCAT_SOURCE]),
    _q("RA4", "style_readiness_comparison", "Al comparar Vintage Port, Tawny con edad y Rutherglen Muscat viejo al salir al mercado, ¿qué interpretación explica mejor su preparación para beber?", "Vintage puede requerir botella y decantación; Tawny y Muscat viejo suelen estar plenamente desarrollados al embotellar.", ["Todos necesitan décadas adicionales en botella.", "Ninguno forma sedimento.", "Tawny mejora más en botella que Vintage."], "Los estilos completan su maduración principal en recipientes distintos.", "Vintage conserva estructura para evolución en botella; los oxidativos se afinan antes del embotellado.", "Cambian la ventana de consumo y el servicio.", "MC_PORT_VINTAGE_01", "Aplicar la misma regla de guarda a todos los fortificados.", ["Vintage Port", "Tawny", "Rutherglen Muscat", "servicio"], [PORT_SOURCE, MUSCAT_SOURCE]),
]


def _slug(value: str) -> str:
    return re.sub(r"[^A-Z0-9]+", "_", value.upper()).strip("_")


def _record(spec: dict, question_id: int, index: int) -> dict:
    letters = ("A", "B", "C", "D")
    correct_letter = letters[index % 4]
    wrong_iter = iter(spec["wrongs"])
    options = {}
    for letter in letters:
        options[letter] = spec["correct"] if letter == correct_letter else next(wrong_iter)
    distractor_rationales = {
        letter: (
            "Es la relación causal correcta."
            if letter == correct_letter
            else f"No explica el mecanismo clave: {spec['mechanism']}"
        )
        for letter in letters
    }
    return {
        "question_id": str(question_id),
        "question_text": spec["stem"],
        "question_type": "theory",
        "expected_topics": [spec["ra"], spec["topic"]],
        "expected_causal_links": [
            f"{spec['cause']} -> {spec['mechanism']} -> {spec['effect']}"
        ],
        "expected_keywords": spec["keywords"],
        "expected_reasoning_type": "cause_effect",
        "difficulty": "intermediate" if index % 3 else "distinction",
        "source_type": "SBA gap closure | manually curated from local official study guide",
        "safe_for_examiner": False,
        "options": options,
        "correct_answer_letter": correct_letter,
        "correct_answer_text": spec["correct"],
        "source_support": {
            "source_ids": [Path(path).stem for path in spec["source_files"]],
            "source_files": spec["source_files"],
            "support_rationale": (
                "Las fuentes locales sustentan el mecanismo, el resultado de estilo "
                "y el contraste diagnóstico evaluado."
            ),
        },
        "enrichment": {
            "causal_chain_candidate": {
                "candidate_id": f"CC_CAND_{_slug(spec['topic'])}",
                "cause": spec["cause"],
                "mechanism": spec["mechanism"],
                "effect": spec["effect"],
            },
            "feedback_profile": {
                "correct_rationale": (
                    f"{spec['cause']} {spec['mechanism']} Por ello, {spec['effect'][0].lower()}"
                    f"{spec['effect'][1:]}"
                ),
                "distractor_rationales": distractor_rationales,
                "remediation_recommendation": (
                    f"Reconstruya la cadena de {spec['topic'].replace('_', ' ')} "
                    "como causa, mecanismo y efecto."
                ),
            },
            "micro_drill_candidate": {
                "prompt": f"Micro-drill: ¿qué efecto sigue a este mecanismo: {spec['mechanism']}?",
                "answer": spec["effect"],
            },
            "misconception_linkage_candidate": {
                "misconception_id": spec["misconception_id"],
                "target_error": spec["target_error"],
            },
        },
        "governance": dict(SAFE_GOVERNANCE),
    }


def build_batch(batch_number: int, start_id: int, specs: list[dict]) -> dict:
    return {
        "schema_version": "sba_gap_closure_batch_v1",
        "batch_id": f"SBA_BATCH_{batch_number}",
        "records": [
            _record(spec, start_id + index, index) for index, spec in enumerate(specs)
        ],
        "governance": dict(SAFE_GOVERNANCE),
    }


def write_batch(batch_number: int, start_id: int, specs: list[dict]) -> Path:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / f"sba_batch_{batch_number:02d}.json"
    path.write_text(
        json.dumps(build_batch(batch_number, start_id, specs), ensure_ascii=False, indent=2)
        + "\n",
        encoding="utf-8",
    )
    return path


def main() -> None:
    print(write_batch(1, 858, BATCH_1))
    print(write_batch(2, 905, BATCH_2))


if __name__ == "__main__":
    main()
